version: '3.8'

services:
  es_search:
    build:
      context: es_search/
      args:
        ELK_VERSION: $ELK_VERSION
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 4096M
        reservations:
          cpus: '1.00'
          memory: 1024M
    volumes:
      - type: bind
        source: ./es_search/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: ./es_search/config/jvm.options
        target: /usr/share/elasticsearch/config/jvm.options
        read_only: true
      - type: bind
        source: $SEARCH_DATA_VOLUME
        target: /usr/share/elasticsearch/data
      - type: bind
        source: $SEARCH_LOG_VOLUME
        target: /usr/share/elasticsearch/logs
    ports:
      - '39201:9200'
      - '39301:9300'
    environment:
      ELASTIC_PASSWORD: admin@2020
      discovery.type: single-node
    restart: always
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kb_search:
    build:
      context: kb_search/
      args:
        ELK_VERSION: $ELK_VERSION
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 500M
    volumes:
      - type: bind
        source: ./kb_search/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - '35602:5601'
    restart: always
    privileged: true
    depends_on:
      - es_search

  es_logs:
    build:
      context: es_logs/
      args:
        ELK_VERSION: $ELK_VERSION
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 4096M
        reservations:
          cpus: '1.00'
          memory: 1024M
    volumes:
      - type: bind
        source: ./es_logs/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: ./es_logs/config/jvm.options
        target: /usr/share/elasticsearch/config/jvm.options
        read_only: true
      - type: bind
        source: $LOGS_DATA_VOLUME
        target: /usr/share/elasticsearch/data
      - type: bind
        source: $LOGS_LOG_VOLUME
        target: /usr/share/elasticsearch/logs
    ports:
      - '49201:9200'
      - '49301:9300'
    environment:
      ELASTIC_PASSWORD: admin@2020
      discovery.type: single-node
    restart: always
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kb_logs:
    build:
      context: kb_logs/
      args:
        ELK_VERSION: $ELK_VERSION
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 500M
    volumes:
      - type: bind
        source: ./kb_logs/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - '45602:5601'
    restart: always
    privileged: true
    depends_on:
      - es_logs

  redis_api:
    build:
      context: redis_api/
      args:
        REDIS_VERSION: $REDIS_VERSION
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 25M
    volumes:
      - type: bind
        source: ./redis_api/config/redis.conf
        target: /usr/local/etc/redis/redis.conf
        read_only: true
    ports:
      - '36379:6379'

networks:
  default:
    external:
      name: $DOCKER_BRIDGE_NETWORK