server.name: kb-logs-docker-vt
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://es_logs:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.username: elastic
elasticsearch.password: admin@2020
